export const Users =[
    {
        id:1,
        profilePicture:"person/1.jpeg",
        username:"hahuh huhuq",
    },
    {
        id:2,
        profilePicture:"person/2.jpeg",
        username:"sdn uhu q",
    },
    {
        id:3,
        profilePicture:"person/3.jpeg",
        username:"dsgg hhthe",
    },
    {
        id:4,
        profilePicture:"person/4.jpeg",
        username:"eryb yee",
    },
    {
        id:5,
        profilePicture:"person/5.jpeg",
        username:"derye ete",
    },
    {
        id:6,
        profilePicture:"person/6.jpeg",
        username:"rehe erge",
    },
    {
        id:7,
        profilePicture:"person/7.jpeg",
        username:"sees wew ",
    },
    {
        id:8,
        profilePicture:"person/8.jpeg",
        username:"wet wtw",
    },
    {
        id:9,
        profilePicture:"person/9.jpeg",
        username:"et etee",
    },
    {
        id:10,
        profilePicture:"person/10.jpeg",
        username:"heje ge ffjr",
    },
];

export const Posts=[
    {
        id:1,
        desc:"thi is descrption about the post",
        photo:"post/1.jpeg",
        date:"5 min ago",
        userId:1,
        like:32,
        comment:9,
    },
    {
        id:2,
        desc:"shhhdhr",
        photo:"post/2.jpeg",
        date:"5 min ago",
        userId:2,
        like:32,
        comment:9,
    },
    {
        id:3,
        desc:"tfjoe fjof kjro rfieht",
        photo:"post/3.jpeg",
        date:"15 min ago",
        userId:3,
        like:3,
        comment:9,
    },
    {
        id:4,
        desc:"t eri wie  irhi whe e post",
        photo:"post/4.jpeg",
        date:"51 min ago",
        userId:4,
        like:12,
        comment:7,
    },
    {
        id:5,
        desc:"ee jh wehi iew eh ost",
        photo:"post/5.jpeg",
        date:"84 min ago",
        userId:5,
        like:342,
        comment:29,
    },
    {
        id:6,
        desc:"jsdh n je fmefef u h yh  post",
        photo:"post/6.jpeg",
        date:"57 min ago",
        userId:6,
        like:62,
        comment:57,
    },
    {
        id:7,
        desc:"tfsnsb nug jf jgys  post",
        photo:"post/7.jpeg",
        date:"65 min ago",
        userId:7,
        like:65,
        comment:75,
    },
    {
        id:8,
        desc:"thad wt r post",
        photo:"post/8.jpeg",
        date:"5 min ago",
        userId:8,
        like:342,
        comment:1,
    },
    {
        id:9,
        desc:"",
        photo:"post/9.jpeg",
        date:"53 min ago",
        userId:9,
        like:32,
        comment:1,
    },
    {
        id:10,
        desc:"thi is descrption about the post",
        photo:"post/10.jpeg",
        date:"5 min ago",
        userId:10,
        like:32,
        comment:9,
    },
]